### ISSUE TITLE
Troupe Delete

### ISSUE THREAD

**Issue by ut-secretary** [wastevens/ElysiumFrontend#14]
Though there is a link for "delete" next to the newly created troupe, clicking it does not actually delete the troupe. Also, some sort of deletion confirmation is vital to prevent accidental deletion of an active troupe.

**Comment by wastevens** [comment]
Unable to reproduce.
![step1](https://cloud.githubusercontent.com/assets/1065558/8173615/4ec818ec-139e-11e5-81f6-6c97dd445fd7.gif)
![step2](https://cloud.githubusercontent.com/assets/1065558/8173616/505e4c08-139e-11e5-8717-4b4c255921bc.gif)

**Comment by undergroundtheater** [comment]
I think this was fixed with the latest push, but let's make sure it's not an ownership issue.  Please try deleting one of the Louisville troupes as a user other than "admin@ut.org" or "technology@undergroundtheater.org".

**Comment by ut-secretary** [comment]
Confirming that I still cannot delete the troupe "Louisville: C/A/IA" using
the admin account secretary@undergroundtheater.org. If I create a new
troupe and attempt to delete it, the delete functions properly. "Test1 -
C/A/IA" deleted with no issue.

Katherine Ray King
Secretary
Underground Theater Inc. Board of Directors

**Comment by wastevens** [comment]
Defect was caused by not properly handling troupe-character and troupe-user relationships when deleting.  Fixed; closing.
